### ISSUE TITLE
SCs First Cut

### ISSUE THREAD

**Issue by WayneEDick** [w3c/low-vision-SC#1]
<h1>Principle Reconfigurable</h1> 

<p>Content enables users to configure the user interface to meet their personal needs.</p>

<h2>Guideline x.1 (Visual Flexibility)</h2> 

<p>The visual presentation of all content can be reconfigured to meet the visual needs of each user.</p>

<dl>
<dt>SC x.1.1 (Reflow)</dt> 
<dd>Content shall enable users to reflow any multi-column presentation to a single column presentation.</dd>
<dt>SC x.1.2 (Word Wrap)</dt> 
<dd>Content shall enable text to word wrap so that lines fit the viewport width regardless of the text size. </dd>
<dd>If a word, URI or any other unbroken text string exceeds the width of the screen then it shall be broken to fit the viewport width. Users can express a choice for hyphenation, word breaking or neither to address the problem of string overflow.</dd>
<dd>If the visual presentation uses indentation to convey meaning, then word wrapping will conform to the indentation pattern to preserve meaning and readability.</dd>
<dt>SC x.1.3 (Color, Contrast, Brightness, Polarity)</dt> 
<dd>Content shall enable colors to be changed using the full spectrum of colors to meet user needs for color perception as well as control over contrast, brightness and polarity.</dd> 
<dt>SC x.1.4 (Resize Text)</dt> 
<dd>Text can be resized to meet the user's visual requirements without creating a need for bi-directional scrolling.</dd>
<dt>SC x.1.5 (Font Family)</dt> 
<dd>Content enables the user to replace the font family (face) chosen by the author with any font family from the full range of fonts available to the author.</dd>
<dt>SC x.1.6 (Font Style) </dt>
<dd>Content enables the user to change the font style of the author to a font family or font style that meets the user's needs.</dd>
<dt>SC x.1.7 (Spacing Text)</dt>
<dd>Content enables the user to change the spacing of lines, characters and words by an amount to meet the user's needs.</dd>
<dt>SC x.1.8 (Spacing Objects)</dt>
<dd>Content shall enable user choice is the spacing between blocks of text, images, lists, lists items and other objects presented within the content.</dd>
<dt>SC x.1.9 (Box Model)</dt>
<dd>Content shall enable users to choose their own box model presentation (Note: This includes all borders, margins and padding).</dd>
<dt>SC x.1.10 (Remove Clutter)</dt>
<dd>Content allows the user to remove any purely decorative images including all background images without losing readability, operability or meaning.</dd>
<dt>SC x.1.11 (Element Level Customization)</dt>
<dd>Content shall enable all of the presentation modifications described in SC x.1.1-x.1.10 at the grammatical element level of the web content.</dd>
</dl>

<p>A <dfn>grammatical element</dfn> of web content is any non-terminal of the programming language that defines the content. The success criterion x.1.11 only applies to elements that are exposed  to the user interface.</p>

**Comment by allanj-uaag** [comment]
all items entered in table http://w3c.github.io/low-vision-SC/GapAnalysis-SC.html
