### ISSUE TITLE
Selectable (User Need 3.4.1, 3.4.2, 3.4.3, 3.4.4, 3.4.5, 3.5.1)

### ISSUE THREAD

**Issue by allanj-uaag** [w3c/low-vision-SC#9]
For the visual presentation of blocks of text, a mechanism is available to achieve the following:
- line spacing can be selected by the user
- word spacing can be selected by the user
- letter spacing can be selected by the user
- text justification can be selected by the user
- margins (blank space) and borders (including color, width, and style) can be selected by the user

**Comment by mraccess77** [comment]
what about paragraph spacing?

**Comment by allanj-uaag** [comment]
Edited
For the visual presentation of blocks of text, a mechanism is available to achieve the following:
- word spacing can be selected by the user
- letter spacing can be selected by the user
- line spacing can be selected by the user
- paragraph spacing can be selected by the user
- text justification can be selected by the user
- margins (blank space) and borders (including color, width, and style) can be selected by the user

**Comment by lauracarlson** [comment]
Is this SC for WCAG 2.1 or Silver?

**Comment by allanj-uaag** [comment]
not for us to decide. I think we create them, put them out for review, then
we can advocate for a particular version.

On Tue, Jul 5, 2016 at 12:12 PM, Laura Carlson notifications@github.com
wrote:

> Is this SC for WCAG 2.1 or Silver?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/w3c/low-vision-SC/issues/9#issuecomment-230541396,
> or mute the thread
> https://github.com/notifications/unsubscribe/AG_WL66CDkLhy-pUFuFDbt-C9J00X9S4ks5qSpCYgaJpZM4JBZ4C
> .

## 

Jim Allan, Accessibility Coordinator
Texas School for the Blind and Visually Impaired
1100 W. 45th St., Austin, Texas 78756
voice 512.206.9315    fax: 512.206.9264  http://www.tsbvi.edu/
"We shape our tools and thereafter our tools shape us." McLuhan, 1964

**Comment by lauracarlson** [comment]
That makes it easier :-) I suspect this one will end up in silver.

**Comment by allanj-uaag** [comment]
closed - created 3 other SC
#12 #11 #10
